# Generated by Django 2.0 on 2018-07-20 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=200)),
                ('jobdescription', models.CharField(max_length=2000)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2018, 8, 19, 15, 38, 23, 866959))),
            ],
            options={
                'verbose_name': 'Job Detail',
            },
        ),
    ]
