# Generated by Django 2.0 on 2018-07-20 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 19, 15, 54, 15, 191836)),
        ),
    ]
