# Generated by Django 2.0 on 2018-07-20 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\d{9,15}$')])),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('resume', models.FileField(upload_to='resume/')),
                ('status', models.CharField(blank=True, choices=[('n', 'Need to verify'), ('a', 'Accept/Shortlist'), ('r', 'Reject')], default='n', max_length=128, null=True)),
                ('applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobDetails')),
            ],
            options={
                'verbose_name': 'List of applicant',
            },
        ),
    ]
